Animations
wolox-training/jm-angular pull request #11
Opened 2020-11-09 14:05 UTC by joacomiguens

## Summary

- Create FadeIn Animation.

## Screenshot

![animations](https://user-images.githubusercontent.com/73898414/98550908-6ffb6400-227b-11eb-8918-7093b2a6159e.gif)

## Trello Card

You can find it [here](https://trello.com/c/QkD9jezj/36-animations)

2020-11-11 16:50 UTC, ebedoyaalzate commented on scss/application.scss
> -@import 'login';
Why you delete this?

2020-11-11 16:51 UTC, ebedoyaalzate commented on scss/application.scss
> -@import 'login';
why you delete this

2020-11-11 16:52 UTC, ebedoyaalzate requested changes

2020-11-11 16:52 UTC, ebedoyaalzate commented on scss/application.scss
> -@import 'login';
You need to delete this?

2020-11-11 16:55 UTC, joacomiguens commented on scss/application.scss
> -@import 'login';
Not at all, I fix it now. 😃

2020-11-11 19:05 UTC, ebedoyaalzate requested changes

2020-11-11 19:05 UTC, ebedoyaalzate commented on scss/application.scss
> -@import 'global-classes';
also this

2020-11-11 19:11 UTC, ebedoyaalzate approved these changes

2020-11-12 15:06 UTC, mcallegari10 approved these changes

2020-11-12 15:35 UTC, merged